name: rerun-actions
description: Rerun other GitHub Actions on pull requests via comment commands.
inputs:
  repo_token:
    description: OAuth or personal access token must be included with the 'repo' scope.
    required: true
  comment_id:
    description: ID of the comment creation event. Set to 'github.event.comment.id'.
    required: true
  allowed_users:
    description: A comma-separated list of GitHub usernames that are allowed to rerun actions.
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "zap"
  color: "blue"
